### ISSUE TITLE
Exception while setting up virtualenv and fabric on Centos 5.9

### ISSUE THREAD

**Issue by tlewis** [scalp42/python-2.7.x-on-Centos-5.x#25]
I am attempting to use your script to install python 27 on a Centos 5.9 virtual machine. The installation proceeds fine until it gets to virtualenv and fabric. Below is the output of the script starting a bit above where the problem begins:

```
Processing setuptools-0.6c11-py2.7.egg
Copying setuptools-0.6c11-py2.7.egg to /opt/python2.7.9/lib/python2.7/site-packages
Adding setuptools 0.6c11 to easy-install.pth file
Installing easy_install script to /opt/python2.7.9/bin
Installing easy_install-2.7 script to /opt/python2.7.9/bin

Installed /opt/python2.7.9/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg
Processing dependencies for setuptools==0.6c11
Finished processing dependencies for setuptools==0.6c11
Searching for pip
Reading http://pypi.python.org/simple/pip/
Best match: pip 6.0.6
Downloading https://pypi.python.org/packages/source/p/pip/pip-6.0.6.tar.gz#md5=bbb17814bdf82187f46aaf9cec6b6caa
Processing pip-6.0.6.tar.gz
Running pip-6.0.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-T1pyUf/pip-6.0.6/egg-dist-tmp-a8y8B3
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 6.0.6 to easy-install.pth file
Installing pip script to /opt/python2.7.9/bin
Installing pip2.7 script to /opt/python2.7.9/bin
Installing pip2 script to /opt/python2.7.9/bin

Installed /opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
The directory '/home/vagrant/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting virtualenv
  Exception:
  Traceback (most recent call last):
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_set.py", line 333, in prepare_files
      upgrade=self.upgrade,
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 305, in find_requirement
      page = self._get_page(main_index_url, req)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 783, in _get_page
      return HTMLPage.get_page(link, req, session=self.session)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 872, in get_page
      "Cache-Control": "max-age=600",
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/sessions.py", line 473, in get
      return self.request('GET', url, **kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/download.py", line 365, in request
      return super(PipSession, self).request(method, url, *args, **kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/sessions.py", line 461, in request
      resp = self.send(prep, **send_kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/sessions.py", line 573, in send
      r = adapter.send(request, **kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/cachecontrol/adapter.py", line 43, in send
      resp = super(CacheControlAdapter, self).send(request, **kw)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/adapters.py", line 370, in send
      timeout=timeout
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
      body=body, headers=headers)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
      self._validate_conn(conn)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
      conn.connect()
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connection.py", line 238, in connect
      ssl_version=resolved_ssl_version)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 254, in ssl_wrap_socket
      return context.wrap_socket(sock)
    File "/opt/python2.7.9/lib/python2.7/ssl.py", line 350, in wrap_socket
      _context=self)
    File "/opt/python2.7.9/lib/python2.7/ssl.py", line 537, in __init__
      raise ValueError("check_hostname requires server_hostname")
  ValueError: check_hostname requires server_hostname

The directory '/home/vagrant/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting fabric
  Exception:
  Traceback (most recent call last):
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/req/req_set.py", line 333, in prepare_files
      upgrade=self.upgrade,
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 305, in find_requirement
      page = self._get_page(main_index_url, req)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 783, in _get_page
      return HTMLPage.get_page(link, req, session=self.session)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 872, in get_page
      "Cache-Control": "max-age=600",
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/sessions.py", line 473, in get
      return self.request('GET', url, **kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/download.py", line 365, in request
      return super(PipSession, self).request(method, url, *args, **kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/sessions.py", line 461, in request
      resp = self.send(prep, **send_kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/sessions.py", line 573, in send
      r = adapter.send(request, **kwargs)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/cachecontrol/adapter.py", line 43, in send
      resp = super(CacheControlAdapter, self).send(request, **kw)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/adapters.py", line 370, in send
      timeout=timeout
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
      body=body, headers=headers)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
      self._validate_conn(conn)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
      conn.connect()
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/connection.py", line 238, in connect
      ssl_version=resolved_ssl_version)
    File "/opt/python2.7.9/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 254, in ssl_wrap_socket
      return context.wrap_socket(sock)
    File "/opt/python2.7.9/lib/python2.7/ssl.py", line 350, in wrap_socket
      _context=self)
    File "/opt/python2.7.9/lib/python2.7/ssl.py", line 537, in __init__
      raise ValueError("check_hostname requires server_hostname")
  ValueError: check_hostname requires server_hostname



Looks like the script exited or got interrupted, cleaning up.
```

**Comment by scalp42** [comment]
I believe it's related to the script running under sudo.

Can you try in the script (just turn the extras off, no need to re-run the script):

```
install_extras="blabla"
```

Then clean up:

```
$> sudo rm -fr .cache
```

and try to run:

```
$> /opt/python2.7.9/bin/pip install fabric
```

Let me know if it fixes the problem.

Thanks for reporting!

**Comment by scalp42** [comment]
I should probably change the extras to not be installed by default. A bit too opinionated.
